version: '3.7'
services:
    mongo:
        image: mongo
        container_name: mongodb
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: case
        ports:
        - 27017:27017
        networks:
        - app-tier
        
    mongo-express:
        image: mongo-express
        restart: always
        ports:
        - 8081:8081
        environment:
            - ME_CONFIG_MONGODB_SERVER=mongodb
            - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
            - ME_CONFIG_MONGODB_ADMINUSERNAME=root
            - ME_CONFIG_MONGODB_ADMINPASSWORD=case
            - ME_CONFIG_BASICAUTH_USERNAME=admin
            - ME_CONFIG_BASICAUTH_PASSWORD=case
        depends_on:
        - mongo
        networks:
        - app-tier

    redis:
      image: "redis:alpine"
      ports:
        - '6379:6379'
      networks:
        - app-tier
        
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:6.6.1
        container_name: case_elastic
        environment:
        - cluster.name=docker-cluster
        - bootstrap.memory_lock=true
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ulimits:
            memlock:
                soft: -1
                hard: -1
        ports:
        - "9201:9200"
        - "9301:9300"
        networks:
        - app-tier

    kibana:
        image: docker.elastic.co/kibana/kibana:6.6.1
        container_name: case_kibana
        ports:
        - "5602:5601"
        networks:
        - app-tier

    case-api:
        image: case/api:latest
        container_name: case-api
        restart: always
        ports:
          - "5000:80"
        build: 
            context: src
            dockerfile: "Case.API/Dockerfile"
        ports:
          - 5000:80
        environment:
          MongoDbSettings__ConnectionString: mongodb://root:case@mongo:27017
          RedisConnectionString: redis:6379
        depends_on:
          - mongo
        networks: 
            - app-tier

networks:
    app-tier:
      name: app-tier