name: Publish Docker Image

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set tag version
        id: tagversion
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: src
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: castielizm/case
          dockerfile: src/Case.API/Dockerfile
          tags: case-api-${{ steps.tagversion.outputs.tag }}
